### PR TITLE
cluster-ui: backport versions from 0.2.16 to 0.2.36

### PR DESCRIPTION
**Pull request by koorosh**
This backport includes changes from `0.2.16` to `0.2.36`, and `0.2.41` that don't depend on `crdb-protobufjs-client` version higher than `0.0.7` and mostly include UI styling fixes.
Following cluster-ui versions aren't backported: `0.2.28`, `0.2.29`, and `0.2.30` because they require crdb-protobufjs-client` version which isn't compatible with cockroachdb 21.1 version

### CODE REVIEW

**Comment by maryliag** [comment]
Is this just until 0.2.36 because all the others after that require protobuf changes?
Is it possible to add the changes from https://github.com/cockroachdb/ui/pull/314/files ? I think this is 0.2.41 
The PR has a change on protobuf but that change was not suppose to be on that PR (I was working on another branch, switch just to fix this minor issue and didn't notice this was added)

**Comment by koorosh** [comment]
> Is this just until 0.2.36 because all the others after that require protobuf changes?
> Is it possible to add the changes from https://github.com/cockroachdb/ui/pull/314/files ? I think this is 0.2.41
> The PR has a change on protobuf but that change was not suppose to be on that PR (I was working on another branch, switch just to fix this minor issue and didn't notice this was added)

`0.2.36` is the version that is currently bumped in CC so it is the most recent version required to "fix" version misalignment for release `21.1`.

I would create separate backport PR for `0.2.41` (and other versions after `0.2.36` if needed) after this PR is merged. It'll allow to keep this PR with only intention to fix versions misalignment.

**Comment by maryliag** [comment]
@koorosh awesome! The more you can include the better! 
I don't have any issue that you should "hold on", so feel free to add anything that you can :D

**Review by nathanstilwell — APPROVED** [review]
Tested on staging. Looks great. LGTM!

**Pull request merged**
