### PR TITLE
ui-components: update README with guidance re: class name prefixing

### PR DESCRIPTION
**Pull request by j-low**
… component CSS modules

# ui-components // update README with guidance re: class name prefixing

#### Checklist
- [x] I have updated the README of the package I'm working in to reflect my changes

### CODE REVIEW

**Comment by nathanstilwell** [comment]
@j-low Can we rebase this and move the style content into `CONTRIBUTING.md`?

**Comment by j-low** [comment]
@nathanstilwell sorry for the late reply, but yes I'd be happy to.

**Comment by nathanstilwell** [comment]
> @nathanstilwell sorry for the late reply, but yes I'd be happy to.

No worries, I know it's low priority. Just trying to not forget about these PRs myself.

**Comment by j-low** [comment]
@nathanstilwell changes pushed

**Pull request merged**
