### PR TITLE
icons: update docs icon, remove outline from play view

### PR DESCRIPTION
**Pull request by lassenordahl**
Adjusts some icons.

Release note: Updates to docs and outline icons

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @cockroachlabs/icons@0.7.11-canary.544.6539174916.0
  npm install @cockroachlabs/ui-components@0.7.12-canary.544.6539174916.0
  # or 
  yarn add @cockroachlabs/icons@0.7.11-canary.544.6539174916.0
  yarn add @cockroachlabs/ui-components@0.7.12-canary.544.6539174916.0
  ```
</details>

### CODE REVIEW

**Comment by laurenbarker** [comment]
@lassenordahl the play button icon looks the same in the preview (e.g still has the outline). Can you confirmed it changed?

**Comment by lassenordahl** [comment]
Yeah, it's updated from what it was. It should be a solid triangle now. Doing hollow triangles is weird, and the previous one had an issue of having the center not be filled with the same color as the outline stroke.

Screenshot 2023-10-16 at 3 43 27 PM

I updated the fill here to make it solid, will discuss with Anne if that's okay design system wise. When testing locally, `fill="inherit"` works properly for accepting the overridden fill values, however the triangle disappears in the preview. 

Using the normal `fill="#hex"` works fine for the preview, and is in line with how the other ones are defined. The value should be overridden on import based on how we define the other SVGs. It appears our coloring system doesn't work for `stroke` values.

**Comment by lassenordahl** [comment]
Just kidding on the above comments. New one has been updated to account for design/export. No longer uses `stroke`, and uses `fill` instead which should resolve the problem. Thanks @Annebirzin !

**Comment by lassenordahl** [comment]
All good now! 

Screenshot 2023-10-16 at 5 02 30 PM

**Review by laurenbarker — APPROVED** [review]
LGTM!

**Comment by lassenordahl** [comment]
tftr!

**Pull request merged**
