### PR TITLE
# Cluster-ui // Removing Cluster-ui

### PR DESCRIPTION
**Pull request by nathanstilwell**
Removing Cluster-ui code as it has been migrated to cockroachdb/cockroach.

### CODE REVIEW

**Review by koorosh — APPROVED** [review]
LGTM

**Comment by laurenbarker** [comment]
@nathanstilwell is this safe to merge? I'm seeing cluster-ui build errors on some new PRs. Looks like this will solve the issue 😄

**Comment by laurenbarker** [comment]
@nathanstilwell happy to take this over if you don't have time. The cluster-ui package is causing a lot of noise which makes me less confident in upgrading dependencies: https://github.com/cockroachdb/ui/pull/343

**Comment by nathanstilwell** [comment]
Replaced by #367

**Pull request closed without merging**
